name:                distributed-kvs-practice
version:             0.1.0.0
github:              "matonix/distributed-kvs-practice"
license:             BSD3
author:              "maton"
maintainer:          "automatonix@gmail.com"
copyright:           "Haruki Yokoyama"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/matonix/distributed-kvs-practice#readme>

dependencies:
- base >= 4.7 && < 5
- distributed-process
- distributed-static
- distributed-process-simplelocalnet
- network-transport-tcp
- containers < 0.6
- template-haskell
- network
- stm

library:
  source-dirs: src

executables:
  db:
    main:                Db.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-kvs-practice

tests:
  distributed-kvs-practice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-kvs-practice
